### ISSUE TITLE
Redis Fix - namespace key can grow to GB size

### ISSUE THREAD

**Issue by kdybicz** [jaredwray/keyv#455] opened 2022-08-30 10:10 UTC
**Describe the bug**
Since I migrated to `keyv` it looks like the amount of freeable memory is declining in constant rate: https://imgur.com/a/77kOTD7 (20 Jul is when I released changes for `keyv` migration).

I expect it to be related to the `namespace:...` key, that in my case can grow to more than 15GB in actively used cache.

**To Reproduce**
I would expect that adding a bunch of big keys for short living values will cause the `namespace:...` size to constantly grow.

**Expected behavior**
I would expect to have some auto-purging mechanism?

**Tests (Bonus!!!)**
N/A

**Additional context**
N/A

**Comment by jaredwray** [comment] 2022-08-31 19:16
HI 👋 @kdybicz - do you have the storage adapter you are using and also how many objects are in there? 

Can we see the code that you are adding in objects and setting the TTL?

Also, have you tried to do a `clear()` and saw what it is doing?

**Comment by kdybicz** [comment] 2022-08-31 19:49
Hi @jaredwray! I did some investigation and I'm no longer so sure that the migration to `keyv` was at fault. Though the fact remain that before I cleared the cache the `namespace:...` exceeded 15 GB.

The only adapter/wrapper I use is https://github.com/kdybicz/apollo-server-compression-cache-wrapper though it's only responsible for compression of the cached data, it doesn't change keys.

I'm using cache only with apollo datasources, so no additional magic there. This is the code I use for the setup:
```
const keyv = new Keyv(process.env.REDIS_HOST, {
  adapter: 'redis',
  namespace: '...',
  lazyConnect: true,
  connectTimeout: 5000,
  reconnectOnError: (error: Error) => {
    log.error(`Reconnect on error: ${error.message}`);
    const targetErrors = [/READONLY/, /ETIMEDOUT/];
    return targetErrors.some((targetError) => targetError.test(error.message));
  },
  retryStrategy: (times: number) => {
    ...
  },
});

const cache = new KeyvAdapter(keyv, { disableBatchReads: true });

const compressedCache = new CompressionCacheWrapper(cache, {
  compress: (data: Buffer) => zlib.brotliCompressSync(data, {
    [zlib.constants.BROTLI_PARAM_MODE]: zlib.constants.BROTLI_MODE_TEXT,
    [zlib.constants.BROTLI_PARAM_QUALITY]: 3,
  }),
  decompress: (data: Buffer) => zlib.brotliDecompressSync(data),
});

const server = new ApolloServer({
  csrfPrevention: true,
  schema: makeExecutableSchema({
    typeDefs: schema,
    resolvers,
  }),
  dataSources: () => ({
    ...
  }),
  cache: compressedCache,
  context: ({ event, context }) => ({
    functionName: context.functionName,
    event,
    context,
  }),
  ...
```

**Comment by jaredwray** [comment] 2022-08-31 22:12
This looks pretty straight forward and we have not had an issue with Redis recently around aging out with time to live. 

Have you tried setting the ttl to a specific time and see if it is doing the right thing by aging out the cache?

**Comment by kdybicz** [comment] 2022-09-01 07:50
I played with the TTL a lot and that's not the problem. All of the keys that I'm caching have the TTL set, beside one which I think is created and controlled by `keyv` or `apollo` itself and it is some sort of intermediate `namespace:...` hash. And that's the object that can grow, because afaik there is no way to set TTL on keys in a hash. So in my case, where keys change a lot and can be long it adds up, slowly but surely. Hope that summary make sense.

**Comment by jaredwray** [comment] 2022-09-03 23:35
I wonder if we can code up an example that does this as a test case. Think you have time to get a simple version that just does it as a unit test?

**Comment by kdybicz** [comment] 2022-09-05 20:42
Hope that helps:
```
test('namespace is not cleaned up by TTL', async t => {
	// Setup
	const keyv = new Keyv(redisURI, {
		adapter: 'redis',
		namespace: 'v3',
	});

	const length = 2048;
	const key = [...Array.from({length}).keys()].join('');

	await keyv.set(key, 'value', 1);

	await new Promise(r => {
		setTimeout(r, 250);
	});

	await keyv.disconnect();

	// Test
	const redis = new Redis(redisURI);

	// Stored key/value does expire
	const expiredValue = await redis.get(`v3:${key}`);
	t.is(expiredValue, null);

	// But the namespace doesn't expire
	t.true(await redis.exists('namespace:v3') === 1);

	// And take out some of the memory for each of the keys
	t.true(await redis.memory('USAGE', 'namespace:v3') === 7336);

	// Even though the value is no longer there
	const storedValue = await redis.mget('namespace:v3', `v3:${key}`);
	t.deepEqual(storedValue, [null, null]);
});
```

**Comment by jaredwray** [comment] 2022-09-08 15:10
@kdybicz - thanks for doing this and we are looking at it now.

**Comment by kdybicz** [comment] 2022-09-21 12:31
@jaredwray have you had a chance to take a look at the problem and think if is solvable on your side?

**Comment by jaredwray** [comment] 2022-09-21 16:08
Hi @kdybicz - @alphmth said they will be looking at this.

**Comment by jaredwray** [comment] 2022-09-29 17:22
@kdybicz - one thing we could do is just not use namespace which most likely would fix the issue. We could make it so the Redis system has an option to not use that.

**Comment by kdybicz** [comment] 2022-09-30 10:52
@jaredwray I think that making it optional might help to solve part of the problem, but as it's not a "real" bug and solution would be partial - as it would not help people wanting to use namespaces - I would hold off with any bigger changes. The fix for "clean" method should be enough, plus maybe some note in docs.

**Comment by loris** [comment] 2022-09-30 11:57
Hi! Can confirm the same issue on our production clusters (`namespace:keyv` set with millions of members) and can easily reproduce it locally.
Actually, I had a quick look at the [redis implementation](https://github.com/jaredwray/keyv/blob/main/packages/redis/src/index.js), the issue is that the members are removed from the namespace key only when cache entries are deleted manually (using `delete` or `clear`), but nothing happen when cache entries are automatically removed by Redis TTL feature (which is probably supposed to be the majority of the keys for a basic cache use-case)

**Comment by jaredwray** [comment] 2022-10-14 20:08
We have added more partial fixes on this https://github.com/jaredwray/keyv/pull/513

**Comment by jaredwray** [comment] 2022-10-27 19:04
@kdybicz @loris - Wanted to get you an update on this storage adapter and what we are planning to do in November. Our current goal is to re-write part of the redis adapter as the usage needs to be enabled to not use the namespace like we are doing today. 

With that said we will be adding in an option to not use the namespace and `might` make that the default moving forward over time. Initially we will make it a feature flag which will solve this issue and we are targeting in November 2022 to do that update.

**Comment by KODerFunk** [comment] 2022-12-06 14:30
I have another issue around `this.redis.sadd(`. 
I use [commandTimeout](https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#commandTimeout) option and some errors dont catch in project-code. As it turned out, these are timeouts on the `sadd` command. Until I figured out why my `catch` does not work and the error goes to `unhandledRejection`.
I need the ability to disable this, I also have to make `class MyKeyvRedis extends KeyvRedis` in the project and override not only the `set` method, but also `clear`.

**Comment by haritonstefan** [comment] 2023-02-06 11:54
Hello @jaredwray I was wondering what's the status of this?
I'm open to help with it.

**Comment by jaredwray** [comment] 2023-02-06 17:57
@haritonstefan - we have started the rewrite but had to work on the test-suite upgrade first which should be releasing this week. Then we will get the new Redis client built and live. 

Note that we are moving the new Redis client to Typescript and also solving for the architecture issues above by not using the namespacing inside redis anymore unless you explicitly set the option to use it. 

Happy for you to help and will ping you next week on the status and plan.

**Comment by dylanseago** [comment] 2023-03-02 18:49
This issue is also impacting us. Started using keyv-redis as a short ttl cache for GET requests. The namespace key has grown massive in size slowly over time as it accumulates every key ever cached without clearing it as ttl expires

**Comment by kaykdm** [comment] 2023-04-03 07:49
> This issue is also impacting us. Started using keyv-redis as a short ttl cache for GET requests. The namespace key has grown massive in size slowly over time as it accumulates every key ever cached without clearing it as ttl expires

We are also facing the same issue.
@jaredwray any update?

**Comment by kdybicz** [comment] 2023-04-03 08:38
As a temporary workaround I've created stupid simple cron Lambda to run once a month and just remove the namespace key in the middle of the night, when the traffic is the lowest. That might not work for all of you, but it kinda solved the issue for me.

**Comment by haritonstefan** [comment] 2023-04-19 06:46
> @haritonstefan - we have started the rewrite but had to work on the test-suite upgrade first which should be releasing this week. Then we will get the new Redis client built and live.
> 
> Note that we are moving the new Redis client to Typescript and also solving for the architecture issues above by not using the namespacing inside redis anymore unless you explicitly set the option to use it.
> 
> Happy for you to help and will ping you next week on the status and plan.

Hi @jaredwray I wanted to follow up on this message, how can I help?

**Comment by jaredwray** [comment] 2023-04-22 23:59
Adding in the namespace disable capability as we are building the next version of `@keyv/redis` now. 

https://github.com/jaredwray/keyv/issues/729

**Comment by jaredwray** [comment] 2023-06-26 20:32
@haritonstefan @PhantomRay @loris @KODerFunk - we have merged the changes in and should be releasing an update with the change to enable or disable using Redis Sets for name spacing in the next 10 days.

**Comment by kdybicz** [comment] 2023-06-26 21:02
@jaredwray amazing news! I will setup myself a reminder to take a look at your changes in the next couple of weeks. Thank you for the update!

**Comment by jaredwray** [comment] 2023-07-01 19:39
@loris @KODerFunk @PhantomRay @haritonstefan @kdybicz - This has now been released with instructions here https://github.com/jaredwray/keyv/releases/tag/2023-07-01

To summarize it:

For high performance environments and to not have the namespace (SETS) grow we are providing an option not to use it. Simply change your code with this option:

```js
const Keyv = require('keyv');
const keyv = new Keyv('redis://user:pass@localhost:6379', { useRedisSets: false });
```

Please let me know your thoughts on this.

**Closed by jaredwray** 2023-07-01 19:39 UTC
Labels: bug, storage adapter, in progress
