### ISSUE TITLE
Extend API to support backends that permit Compare-and-Swap for caching without a race condition

### ISSUE THREAD

**Issue by gjbadros** [jaredwray/keyv#756] opened 2023-03-31 21:06 UTC
Seems like
```js
if (!await keyvMap.has(someKey)) { 
  const someValue = ...expensive computation and or side effects ...
  keyvMap.set(someKey, someValue)
}
```
is used by folks a lot but it has a race condition when that code block is re-entrant (e.g., an HTTP or GraphQL handler). keyv has a nice API, but it doesn't expose a proper Compare&Swap or SetIfUnset/SetNX functionality to allow using a backend such as redis that could support this pattern without the race condition.

Perhaps there could be an optional 4th argument to .set() to indicate the desire to return the old value or an new .getSet() function that returns a promise for the existing value instead of just uselessly returning true?

Then we can write:

```js
if (!await keyvMap.getSet(someKey, 'in_progress')) {
  const someValue = ...expensive computation and or side effects ...
  keyvMap.set(someKey, someValue)
}
```

Or similar.  I just want to get rid of the race condition when the first processor hitting the await switching to a second processor at the same codepoint happens so both `.has()` invocations return false and we do the computation and have the side-effects multiple times.

Thoughts?

**Comment by jaredwray** [comment] 2023-04-21 19:53
@gjbadros - thanks for sending this in and I do think that this would break many of the storage adapters by adding this in. I do understand that this is not as performant as you can get with using Redis directly. 

We are trying to stay as much on the `Map()` API layer with some additional functions that have been slowly rolled out. 

I would love to see a couple examples of other API's / libraries that are doing this and code examples to learn more before we just close this as something we are not going to do. 

We could move to `async` but the issue is that removes the compatibility with others. Thoughts?

**Comment by gjbadros** [comment] 2023-04-21 21:37
And it seems like making the set possibly return the prior value for backends that support it would an easy and good change. Given that some backends would see a performance hit to get and set, you could make it a new method or an extra argument to the setter that only some backends support.

What do you mean by "move to `async`"?

**Comment by jaredwray** [comment] 2023-04-22 17:18
Most likely it would have to be a new method as we try not to break other clients out there and standardize on our current interfaces.

**Comment by gjbadros** [comment] 2023-04-22 20:27
So just a getAndSet() method supported by redis and memcache backends?

**Comment by jaredwray** [comment] 2023-04-22 23:57
Yeah. I think at this time we will most likely not add this as I would want most of the storage adapters to support this. Closing this option for now and will rethink it over this year as something that we will want to extend.

**Closed by jaredwray** 2023-04-22 23:57 UTC
Labels: enhancement, investigating

**Comment by gjbadros** [comment] 2023-04-23 00:14
I recommend at least documenting the race condition.
